# Generated by Django 3.2.7 on 2021-09-21 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('french', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='search',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
